image: node:alpine

stages:
  - install
  - lint-code
  - build
  - deploy

cache:
  key: vitepro
  paths: 
    - node_modules

job_install:
  stage: install
  tags: 
    - vite
  script:
    - npm install


job_build:
  stage: build
  tags: 
    - vite
  script:
    - npm run build


job_deploy:
  stage: deploy
  image: docker
  tags: 
    - vite
  script:
    - docker build -t viteimages .
    - if [ $(docker ps -aq --filter name=mylive-container) ]; then docker rm -f mylive-container;fi
    - docker run -d -p 8001:80 --name mylive-container folive
    - echo 'deploy docker image success. visit http://8.135.98.62:8001'